# this dockerfile is used to watch the less file & compile it upon change
FROM klaemo/couchdb
ADD local.ini /usr/local/etc/couchdb/
ADD local.ini /usr/local/etc/
ADD local2.ini /usr/local/etc/couchdb/
ADD local2.ini /usr/local/etc/